---
# Slurm bwuni cpu
name: "SLURM"   # MUST BE "SLURM"
partition: "single"  # "single" for cpu, "gpu_4" or gpu_8" for gpu
job-name: "ppo_debugging"# this will be the experiment's name in slurm
num_parallel_jobs: 99 # max number of jobs executed in parallel
ntasks: 1   #  leave that like it is
cpus-per-task: 8   # there are 10 cores for each GPU
time: 1000   # in minutes
mem-per-cpu: 2000

---
# Experiment 1
name: "ppo_debugging"

# Required: Can also be set in DEFAULT
path: "cw_log/"   # location to save results in
repetitions: 5    # number of times one set of parameters is run
iterations: 1 # number of iterations

# Experiment Parameters:
params:
  exp_name: "local_debug_ppo"
  action_type: "velocity" # either 'velocity' or 'continuous'

  normalize_obs_static: False
  normalize_obs_dynamic: True
  total_timesteps: 1.0e+06

  seed: 1
  learning_rate: 2.5e-5 # initial value, then linear decrease. Default is 2.5e-4

  # Environment params
  create_scene_kwargs: {
    "eye_config": [ [ 60, 10, 0, 90 ] ],# [10, 10, 0, 90], [10, 60, 0, -45], [60, 60, 0, 90]]
    "eye_reset_noise": {
      "low": [ -15.0, -15.0, 0.0, -35.0 ],
      "high": [ 15.0, 15.0, 0.0, 35.0 ]
    },

    "rope_stiffness": { # vary young modulus parameter of rope in this range
      "min": !!python/float 5e4, #8e3,
      "max": !!python/float 5e4 # 1e5
    },
    'control_gripper_aperture': False,
    "randomize_gripper": False,
    "start_grasped": True,
    "randomize_grasp_index": False,
  }

  reward_amount_dict: {
    "passed_eye": 10.0,
    "lost_eye": -20.0,  # more than passed_eye
    "goal_reached": 100.0,
    "distance_to_active_eye": -0.0,
    "lost_grasp": -0.1,
    "collision": -0.1,
    "floor_collision": -0.1,
    "bimanual_grasp": 0.0,
    "moved_towards_eye": 200.0,
    "moved_away_from_eye": -200.0,
    "workspace_violation": -1.0,
    "state_limit_violation": -0.01,
    "distance_to_lost_rope": -0.0,
    "delta_distance_to_lost_rope": -0.0,
    "fraction_rope_passed": 0.0,
    "delta_fraction_rope_passed": 200.0,
  }

  num_rope_tracking_points: 0

  changing_context: False # TODO: Make this do something